### ISSUE TITLE
PropertyControlStrings can't be resolved for PropertyFieldDateTimePicker control.

### ISSUE THREAD

**Issue by IsYet1** [SharePoint/sp-dev-fx-property-controls#1]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://github.com/SharePoint/sp-dev-fx-property-controls/wiki) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [  Beta.1  ]

#### Expected / Desired Behavior / Question
Solution should build and run in the workbench.

#### Observed Behavior
Get multiple errors during build. Errors are that PropertyControlStrings can't be resolved.
I think this is used in multiple files in the package.
Example:
`./node_modules/@pnp/spfx-property-controls/lib/propertyFields/dateTimePicker/PropertyFieldDateTimePickerHost.js
Module not found: Error: Can't resolve 'PropertyControlStrings' in '/mnt/c/Dev/sp/lrn/spfx/react00/node_modules/@pnp/spfx-property-controls/lib/propertyFields/dateTimePicker`

#### Steps to Reproduce
Install packages
Add Property Pane field
gulp serve

Thanks!

**Comment by estruyf** [comment]
Thanks for sending this in.

To solve this right now, you have to add the resource file of the property controls to the **localizedResources**. 

You could do this by opening the `config/config.json` and add the following line to the `localizedResources` property:

```json
"PropertyControlStrings": "./node_modules/@pnp/spfx-property-controls/lib/loc/{locale}.js"
```

**Comment by IsYet1** [comment]
That worked. :-)

**Comment by devinprejean** [comment]
FYI, just used this today for PropertyFieldCollectionData and i got the same error.

**Comment by estruyf** [comment]
@devinprejean this is in the documentation on the start page under getting started and all controls point to it. As mentioned, from the next version you do not have to manually configure it anymore.
