### ISSUE TITLE
Ability to refresh PropertyFieldListPicker target site while pane is open

### ISSUE THREAD

**Issue by zshane15** [SharePoint/sp-dev-fx-property-controls#109]
#### Category
- [x] Enhancement
- [ ] Bug
- [X] Question

#### Version
[1.11.0]

#### Expected / Desired Behavior / Question
Is there a way to refresh/update the webAbsoluteUrl property of a PropertyFieldListPicker field while the pane is open? I have a custom string property named siteUrl which is used to populate the webAbsoluteUrl property for a list picker. When the pane opens, and the siteUrl field is populated, the list picker works.

However, when I try changing the siteUrl field, it doesn't update the list picker. I have to close the pane and reopen it. So is there a way to reinitialize the pane while open after a field changes? Basically this would work similar to a cascading drop-down, the user needs to enter a Site Url before they can access the list picker.

I've tried the following:

    protected onPropertyPaneFieldChanged(propertyPath: string, oldValue: any, newValue: any): void {
      if (propertyPath === 'siteUrl' && newValue) {
        ...
        this.context.propertyPane.refresh();
      }

This is how my list picker is setup:

    PropertyFieldListPicker('listSelect', {
      ...
      onPropertyChange: this.onPropertyPaneFieldChanged.bind(this),
      properties: this.properties,
      context: this.context,
      webAbsoluteUrl: this.properties.siteUrl,
    })

#### Observed Behavior
Property pane does not refresh the context for a PropertyFieldListPicker which uses a custom webAbsoluteUrl property which is based on a string field in the property pane.

**Comment by waldekmastykarz** [comment]
I stumble upon exactly the same. It seems that loading lists from the specified site happens only on component mount rather than when properties have been changed.

**Comment by estruyf** [comment]
@zshane15 this would be a good update to the control. Will add it as an enhancement.

**Comment by estruyf** [comment]
I have implemented an enhancement to the single and multi-list picker controls. Feel free to test out the latest beta. More information about how you can do this can be found here: https://sharepoint.github.io/sp-dev-fx-property-controls/beta/

**Comment by zshane15** [comment]
Thanks @estruyf the beta works great! Exactly what I needed.

**Comment by harshdamaniahd** [comment]
Tested and works
