### ISSUE TITLE
PropertyFieldCollectionData text box issues

### ISSUE THREAD

**Issue by joelfmrodrigues** [SharePoint/sp-dev-fx-property-controls#113]
#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [    1.11.0     ]

#### Expected / Desired Behavior / Question
Being able to safely edit values on text boxes

#### Observed Behavior
When editing the text boxes of the test web part within the project, first name and last name start behaving badly.

#### Steps to Reproduce
Run the project and edit the test web part provided.
Click to manage manage collection data on web part properties.
Start typing on one of the text boxes and
Immediately after typing some characters, press backspace to delete a few characters
Immediately after deleting the characters, add a few more
Notice that the control starts to continuously update the value 
Looking at the browser console, we can see that the value being logged is not behaving as expected, which seems like some issue with asynchronous code

**Comment by estruyf** [comment]
Hi @joelfmrodrigues it was indeed a bug.

Current behavior in `v1.12.0`:

![debounce-issue](https://user-images.githubusercontent.com/2900833/49581058-0668d180-f951-11e8-8f69-5a4887e710a6.gif)

Added a fix to resolve this issue:

![debounce-issue-fix](https://user-images.githubusercontent.com/2900833/49581086-1680b100-f951-11e8-930e-3dba60af086d.gif)
