### ISSUE TITLE
Load labels for terms in Taxonomy Picker

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-fx-property-controls#120]
#### Category
- [x] Enhancement
- [ ] Bug
- [x] Question

#### Version

Please specify what version of the library you are using: [1.12.0]

#### Expected / Desired Behavior / Question
Hey folks!
What do you think about adding a feature of requesting labels for terms in Taxonomy Picker?
My initial idea is to add a property, something like `includeLabels`.
If it is set to true then we request labels for the terms.
And here I have two possible ways to code it that I want to discuss:
1. We can load the labels right after the terms are loaded: `GetAllTerms` first and then `GetAllLabels` for the terms in a batch.
2. We can load the labels for the term when it is picked by a user. It will potentially decrease amount of data transferred.

Additionally (and it is partially related to #70) we could start using `@pnp/sp-taxonomy` to simplify requests for the term store items.

Please, share your thoughts on that.

**Comment by AJIXuMuK** [comment]
@estruyf 
I'll start working on the control probably later this week.
I'll be aiming a separate controls, say, `EnterpriseTaxonomyPicker`.
It will use separate "service" for getting terms info that will be also implemented as a separate class, not new methods in existing Taxonomy service. In that case new control will be totally separated.

For now I'll be working on lazy loading (#70) and labels.

And later we can discuss actions as I didn't completely get the idea for now :) 

No ETA for now...

Does it work?

**Comment by estruyf** [comment]
@AJIXuMuK that sounds great! I will see your PR coming.

**Comment by AJIXuMuK** [comment]
@estruyf there are few things I want to resolve in `@pnp/sp-taxonomy` before implementing this one.
[https://github.com/pnp/pnpjs/issues/420](https://github.com/pnp/pnpjs/issues/420) and
[https://github.com/pnp/pnpjs/issues/419](https://github.com/pnp/pnpjs/issues/419)

**Comment by AJIXuMuK** [comment]
One more issue from `@pnp/sp-taxonomy` to track: [#449](https://github.com/pnp/pnpjs/issues/449)
