### ISSUE TITLE
PropertyFieldCodeEditor- Handle initial value update when new props

### ISSUE THREAD

**Issue by FranckyC** [SharePoint/sp-dev-fx-property-controls#121]
In the PropertyFieldCodeEditor field, the initial value is only set at mount time and can't be updated afterwards. It could useful to handle the value update when receiving new props.

This scenario happens in the react-search-refiners sample when the user chooses a different layout resulting to initial value to be updated for the selected layout.

#### Category
- [ X] Enhancement
- [ ] Bug
- [ ] Question

#### Version

Latest

**Comment by estruyf** [comment]
A fix has just been added for this issue. Feel free to test out the latest beta to check if it is fixed for your solution. More information about installing a beta version can be found here: https://sharepoint.github.io/sp-dev-fx-property-controls/beta/

**Comment by FranckyC** [comment]
Thanks @estruyf! I'll test this ASAP.

**Comment by FranckyC** [comment]
@estruyf Unfortunately, it doesn't work. After reviewing your commit it seems you take `props` instead of `nextProps` when setting the new code value. Should it be nextProps instead?

```
this.setState({
        code: typeof this.props.initialValue !== 'undefined' ? this.props.initialValue : ''
      });
```

**Comment by estruyf** [comment]
My mistake will update it right away.

**Comment by estruyf** [comment]
Fix is in, and the beta release should be out in any minute now.

**Comment by FranckyC** [comment]
Works like a charm! Thanks @estruyf  
![untitled project](https://user-images.githubusercontent.com/5659122/49609759-78014980-f96a-11e8-9a83-e900d9a53da8.gif)

**Comment by DanSantoDomingo** [comment]
Hello im new to sharepoint framework and react.. what i want to do is set the webpart code as the initial value.. i tried putting this.domElement but wont work.. also what should i put inside the onPropertyChange to save the changes?
