### ISSUE TITLE
Sorting the data in PropertyFieldCollectionData collectionData

### ISSUE THREAD

**Issue by jesseve** [SharePoint/sp-dev-fx-property-controls#123]
[X] Question

#### Version

Please specify what version of the library you are using: [1.12.0]

I am using the PropertyFieldCollectionData control and have a list of items set up for the collectionData. When I display the collection data the order is random and not same as shown in the control popup. I tried adding a number field but it allows for duplicate values and I couldn't attach any event listeners to the field.

I'm looking for something similiar as the custom sort order in SharePoint term store.

My question is that is it possible to have/create a sorting field for the PropertyFieldCollectionData control and if yes, how could it be done?

**Comment by estruyf** [comment]
@jesseve that would be a great enhancement for the control!

**Comment by estruyf** [comment]
@jesseve this has now be implemented and will be available with the `v1.13.0` release. Feel free to test out the latest beta to see if it fit your needs. More information about installing a beta version can be found here: https://sharepoint.github.io/sp-dev-fx-property-controls/beta/

**Comment by jesseve** [comment]
Wow, that was fast. I will test this out, thank you!
