### ISSUE TITLE
PropertyFieldTermPicker: Layout Issues

### ISSUE THREAD

**Issue by karokuusikallio** [SharePoint/sp-dev-fx-property-controls#143]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://sharepoint.github.io/sp-dev-fx-property-controls/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
- [ ] Enhancement
- [X ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [     1.12 and 1.13.1    ]

########

Version 1.12 had a layout problem with IE11 because {flex-wrap: wrap} requires a width, or preferably max-width for the terms not to overflow to the right outside the screen. 

Version 1.13.1 has a problem with both IE11 and Chrome. Each term is now set to not to wrap so each term is on a different row. This create a problem with terms with long names as the container overflows to the right again.

In both situations there's a problem that the term selection button is not available if the term container overflows.

My suggestion for a fix is to go back to how is was in 1.12 so that the terms wrap nicely if possible and just to add max-width property to make sure that it works with IE11 too.

Thanks!

**Comment by estruyf** [comment]
Thanks for logging this issue, will check what is going on here. As nothing has been changed to the control in version `1.12.0`, `1.13.0` and `1.13.1` it could be related to Office UI Fabric or SharePoint styling.

**Comment by estruyf** [comment]
@karokuusikallio would you be able to include some screenshots to show the issue and the expected result?

**Comment by estruyf** [comment]
I have implemented a change. The tags should now show up as follows:

![screenshot 2019-01-21 15 02 14](https://user-images.githubusercontent.com/2900833/51482963-1836f480-1d98-11e9-9c1b-ad694a929835.png)

Feel free to test out the latest beta which includes this fix. More information about this can be found here: https://sharepoint.github.io/sp-dev-fx-property-controls/beta/

**Comment by estruyf** [comment]
The fix has been released in `1.14.0`, if it would still occur, feel free to reopen the issue.
