### ISSUE TITLE
[PropertyFieldDropdownWithCallout]: Options of type "Divider" and "Header" are ignored

### ISSUE THREAD

**Issue by spplante** [SharePoint/sp-dev-fx-property-controls#145]
#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Version
1.13.1

#### Expected / Desired Behavior / Question
When using the **PropertyFieldDrdopdownWithCallout**, we should be able to specify options that have their **type** property set to **PropertyPaneDropdownOptionType.Header** or **PropertyPaneDropdownOptionType.Divider** in order to display headers and dividers accordingly in the options.

#### Observed Behavior
While the out-of-the-box **PropertyPaneDropdown** does renders **header** and **divider** options correctly, it seems like the **PropertyFieldDrdopdownWithCallout** is only looking at the **key** and **text** property in order to renders the options, which leads to the headers and dividers being rendered as regular selectable options.

#### Steps to Reproduce
Use the  **PropertyFieldDrdopdownWithCallout** with some headers and dividers and see the resulting options.

**Comment by AJIXuMuK** [comment]
Will look into it...

**Comment by AJIXuMuK** [comment]
Finally looked into it :) The fix has been committed

**Comment by spplante** [comment]
Great news thanks!

**Comment by estruyf** [comment]
This will be available in the `1.14.2` release and can already be tested in the latest beta.

Here you can read how you can install the latest beta: https://sharepoint.github.io/sp-dev-fx-property-controls/beta/

**Comment by estruyf** [comment]
This has just been released in version `1.15.0`.

**Comment by spplante** [comment]
Just tested this and it works as expected 👍 

Thanks!
