### ISSUE TITLE
make webpart controls usable in propertypane

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-fx-property-controls#15]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://github.com/SharePoint/sp-dev-fx-property-controls/wiki) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[ ] Bug

[x ] Question

so why do w have. separate repo  for property pane controls , an another for controls to be used in the body of a webpart? is it possible to encapsulate a controls that can be used in a webpart so that it could also be used in  a property pane? could save a lot of effort.
Thanks!

**Comment by estruyf** [comment]
The reasoning is that all the property pane controls are by default React. 

The controls you'll be using could be written in the language of your preference. If you, for example, use Angular, you will not be able to use the React controls directly in your solutions. 

That is why we split these two projects. The property pane controls will stay React only, but for the body controls, we could in the future create new repositories to support other languages, depending on the interest.
