### ISSUE TITLE
PropertyFieldChoiceGroupWithCallout: iconProps not working

### ISSUE THREAD

**Issue by spplante** [SharePoint/sp-dev-fx-property-controls#154]
#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Version
1.13.1

#### Expected / Desired Behavior / Question
When using the **PropertyFieldChoiceGroupWithCallout**, specifying the **iconProps** property in combination with the **officeFabricIconFontName** should render choice buttons with an icon instead of a regular radio button, just like the OOTB **PropertyPaneChoiceGroup**

#### Observed Behavior
When using the **iconProps** as below, the choice group does render buttons instead of radio buttons, but the icon is missing, leaving empty choice buttons instead :

```javascript
{
    key: 'Option1',
    text: 'Option #1',
    iconProps: {
        officeFabricIconFontName: 'BulletedList2'
    }
}, 
```

#### Steps to Reproduce
Use the **PropertyFieldChoiceGroupWithCallout** control and specify an option using the code below, and notice the icon missing :

```javascript
{
    key: 'Option1',
    text: 'Option #1',
    iconProps: {
        officeFabricIconFontName: 'BulletedList2'
    }
}, 
```

**Comment by AJIXuMuK** [comment]
Hi @spplante!
Thanks for reporting.
The fix has been made in #166

**Comment by spplante** [comment]
Awesome good work 👍

**Comment by spplante** [comment]
Just tested this and it works as expected 👍 

Thanks!
