### ISSUE TITLE
Code editor  Property control

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-fx-property-controls#16]
#### Category
[x ] Enhancement

[ ] Bug

[ ] Question

Create a property control that lets users edit  code snippets using the ace editor. Coul let users edit Caml to be used in webparts, html snipperts for handlebars. Json snippets for general purpose stuff.  Would be super useful.

See https://ourcodeworld.com/articles/read/562/how-to-use-properly-ace-editor-in-reactjs

I'm going to try implementing over the holidays (just for fun)

**Comment by russgove** [comment]
I made a copy  of the PropertyPane picker and converted it to a code editor. Works awesome! Has support (i.e. highlighting, autocomplete ) for editing json, javascript sass typescript html, etc.

I 'll have a commit next week. I can think of dozens of uses for this!

source is on my fork https://github.com/russgove/sp-dev-fx-property-controls/tree/dev/src/propertyFields/codeEditor

**Comment by russgove** [comment]
submitted PR

**Comment by estruyf** [comment]
Thanks for your contribution @russgove, we will review this control.

**Comment by estruyf** [comment]
Closing the issue as it is implemented.
