### ISSUE TITLE
PropertyFieldTextWithCallout still persist property value when error

### ISSUE THREAD

**Issue by spplante** [SharePoint/sp-dev-fx-property-controls#172]
#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Version
1.14.1

#### Expected / Desired Behavior / Question
With the **PropertyFieldTextWithCallout** control, when an error is returned from the **onGetErrorMessage** callback property after the text has changed, the WebPart property should not get persisted with the invalid value and should keep it's old value, just like the OOTB TextField property pane.

#### Observed Behavior
When the **onGetErrorMessage** returns an error because the value is invalid, the WebPart property still persists the invalid value.

#### Steps to Reproduce
Use the **PropertyFieldTextWithCallout**, return an error from the the **onGetErrorMessage** callback and notice how the value still gets persisted.

**Comment by estruyf** [comment]
@spplante - @AJIXuMuK implemented a fix for this and is now available in the latest beta. Feel free to test it out.

More information on how you can install the latest beta can be found here: https://sharepoint.github.io/sp-dev-fx-property-controls/beta/

**Comment by estruyf** [comment]
This has just been released in version `1.15.0`.

**Comment by spplante** [comment]
Just tested this and it works as expected 👍 

Thanks!
