### ISSUE TITLE
Callout icon missing with 1.8.2 web part

### ISSUE THREAD

**Issue by c-eiser13** [SharePoint/sp-dev-fx-property-controls#178]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://sharepoint.github.io/sp-dev-fx-property-controls/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
- [ ] Enhancement
- [X ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [     1.14.1    ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
MS Info icon renders to the right of the link/button/label.

#### Observed Behavior
I am trying to use PropertyFieldLinkWithCallout in a 1.8.2 SPFx web part and the icon does not show up. I tested downgrading to 1.12.0 and 1.13.0 and both exhibit same behavior in a 1.8.2 web part. I then switched over to a 1.7.1 web part and the Info UIF icon displays correctly. 
SPFx 1.8.2 web part:
![1 8 prop pane](https://user-images.githubusercontent.com/42096464/57711866-2f466e80-7635-11e9-843a-96f338072097.PNG)

SPFx 1.7.1 web part:
![1 7 prop pane](https://user-images.githubusercontent.com/42096464/57711881-379ea980-7635-11e9-85f9-a50cde84dd9b.PNG)

1.8.2 in browser:
![1 8browser](https://user-images.githubusercontent.com/42096464/57711920-45ecc580-7635-11e9-9250-f428504480f3.PNG)

![1 80x0](https://user-images.githubusercontent.com/42096464/57712315-f955ba00-7635-11e9-9af7-933578f3547f.PNG)

![1 8css](https://user-images.githubusercontent.com/42096464/57712321-fc50aa80-7635-11e9-9d79-8e9ef20abea1.PNG)

1.7.1 in browser:
![1 7browser](https://user-images.githubusercontent.com/42096464/57712683-a3cddd00-7636-11e9-815c-d1d1dc8a4be5.PNG)

Icon Inspected:
![1 7 font family](https://user-images.githubusercontent.com/42096464/57712747-bfd17e80-7636-11e9-848d-61a5c3783285.PNG)

Main difference I can see is the font-family is correct in 1.7.1 and not in 1.8.2. If there is anything else I can provide to assist, just let me know. Thanks for the great set of controls!

#### Steps to Reproduce
Create a new 1.8.2 SPFx web part and add any callout control to the property pane.

**Comment by AJIXuMuK** [comment]
Thank you @c-eiser13 for reporting the issue.
I've added the PR that will fix the issue for the latest versions of SPFx.

**Comment by c-eiser13** [comment]
Thanks for the quick response @AJIXuMuK ! I found a similar issue in the fileTypeIcon control and I've logged an issue in that repo as well.

**Comment by estruyf** [comment]
@AJIXuMuK thanks for fixing this.

@c-eiser13 this is now implemented in the latest beta, feel free to test it out. Here you can read how you can install the latest beta: https://sharepoint.github.io/sp-dev-fx-property-controls/beta/

**Comment by c-eiser13** [comment]
Thanks @AJIXuMuK  and @estruyf I've installed the beta and can confirm it is fixed. Appreciate the quick turnaround!

**Comment by estruyf** [comment]
This has just been released in version `1.15.0`.
