### ISSUE TITLE
Can not set property 'Operation' of undefined

### ISSUE THREAD

**Issue by pinalrana41** [SharePoint/sp-dev-fx-property-controls#18]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://github.com/SharePoint/sp-dev-fx-property-controls/wiki) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[* ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [         ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

#### Submission Guidelines
_Delete this section after reading_
- All suggestions, questions and issues are welcome, please let us know what's on your mind.
- Remember to include sufficient details and context.
- If you have multiple suggestions, questions, or bugs please submit them in separate issues so we can track resolution.

Thanks!

**Comment by estruyf** [comment]
Hi @pinalrana41, it appears something went wrong submitting your issue. Can you create a new one or update this one to get more information about the problem?

**Comment by estruyf** [comment]
This has been fixed as of version 1.2.0.
