### ISSUE TITLE
Additional controls missing callout icon in 1.8.2 web parts 

### ISSUE THREAD

**Issue by c-eiser13** [SharePoint/sp-dev-fx-property-controls#182]
#### Category
- [ ] Enhancement
- [ x] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [         ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
Using Toggle with callout in 1.8.2 web part and info icon is visible.

#### Observed Behavior
When using any property control that references common/propertyFieldHeader instead of common/placeholderWithCallout, the info icon is missing. Looking at the fix that was made in common/placeholderWithCallout, I've created a PR and made the same update in common/propertyFieldHeader ([#178](https://github.com/SharePoint/sp-dev-fx-property-controls/issues/178)) and the callout controls relying on this now work properly.

I will update this post with the PR info.

#### Steps to Reproduce
Create 1.8.2 SPFx project and use Text with callout or toggle with callout (others as well).

Thanks!

**Comment by estruyf** [comment]
This PR got merged and will be available in version `1.16.0`. You can already test it out via installing the latest beta version.
