### ISSUE TITLE
ListPicker add ability to filter the control in other ways

### ISSUE THREAD

**Issue by araver** [SharePoint/sp-dev-fx-property-controls#184]
#### Category
- [X] Enhancement
- [ ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [1.15.0]

#### Expected / Desired Behavior / Question
Ability to filter list using something other than list template

I think it would be nice to have a promiselike callback that would allow the developer to filter, or possibly a filter string that could be sent on the "GET" request or both.

I've seen "listsToExclude" but I think there are better ways to implement this.

I'd be happy to create a PR.

**Comment by estruyf** [comment]
This enhancement will be included in version `1.16.0`. You can already test it out via installing our latest beta version.
