### ISSUE TITLE
PropertyFieldDatetimePicker not calling onPropertyPaneFieldChanged

### ISSUE THREAD

**Issue by steevinBradlee** [SharePoint/sp-dev-fx-property-controls#186]
#### Category
- [x ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

I'm trying to save two date times using this control but the property is never saved, nor is it present in this.properties. onPropertyPaneFieldChanged isn't being called which I'm guessing is the issue.

Here's my initialization of the picker, along with the versions of pnp and the generator I'm using. I'm sure I'm just doing something wrong with the initialization of the picker but I'm not sure.

`PropertyFieldDateTimePicker('startDate', {
                  label: 'Start Date and Time',
                  initialDate: this.properties.startDate,
                  dateConvention: DateConvention.DateTime,
                  timeConvention: TimeConvention.Hours12,
                  onPropertyChange: this.onPropertyPaneFieldChanged,
                  properties: this.properties,
                  onGetErrorMessage: (error) => { return error; },
                  deferredValidationTime: 0,
                  key: 'startDateFieldId'
                })`

"@microsoft/generator-sharepoint": "^1.8.0",
"@pnp/spfx-property-controls": "^1.14.1",
"react": "16.7.0",
"react-dom": "16.7.0",

**Comment by AJIXuMuK** [comment]
Hi @steevinBradlee,
I tested it out and it works fine both in Reactive and non Reactive modes.
You can find the code here: [https://github.com/AJIXuMuK/issues/tree/master/property-controls-186](https://github.com/AJIXuMuK/issues/tree/master/property-controls-186). But basically, it's the same as yours.

<img width="684" alt="Screen Shot 2019-06-12 at 5 13 58 PM" src="https://user-images.githubusercontent.com/17036219/59394778-deaa5a00-8d35-11e9-93b0-d63a0e2b896e.png">

**Comment by estruyf** [comment]
@steevinBradlee can you verify the answer from @AJIXuMuK?

**Comment by steevinBradlee** [comment]
@estruyf  @AJIXuMuK  I wasn't able to get this working in the project I added it to but was able to create a new project and it worked fine. I'd like to investigate more but I think it's probably safe to close this. Thanks for your help!
