### ISSUE TITLE
Sortable multi-field picker

### ISSUE THREAD

**Issue by CStahlberg** [SharePoint/sp-dev-fx-property-controls#19]
#### Category
[x ] Enhancement

[ ] Bug

[ ] Question

I am trying to achieve a webpart which displays information about the current website in a kind of bulletin list or profile style e.g. Projectname, Projectnumber, Budget, Project Responsible... which are stored in a list in the current site.
For this it would be awesome to have a controll that allows to select and order fields from a list.

Ideally, you could move the fields (up, down) into the order you would want them to be used in the webpart and the attached property would return a sorted list of fields. 

I guess you could also use this to specify the order of fields in a list view.

**Comment by estruyf** [comment]
Released with `v1.6.0`.
