### ISSUE TITLE
Docs: all the getting started links are broken

### ISSUE THREAD

**Issue by baywet** [SharePoint/sp-dev-fx-property-controls#191]
#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Version
Please specify what version of the library you are using: Documentation related issue.

#### Expected / Desired Behavior / Question
Getting started link to point to the proper page (eg for this page https://sharepoint.github.io/sp-dev-fx-property-controls/controls/PropertyPaneWebPartInformation/)

#### Observed Behavior
Getting started points to a in-existing page, (notice the controls path section which shouldn't be there)

#### Steps to Reproduce
Open this page https://sharepoint.github.io/sp-dev-fx-property-controls/controls/PropertyPaneWebPartInformation/ click on Getting Started

#### Potential fixes
I'm not sure whether we should replace the link by `../#getting-started` or `index.md#getting-started` (so MkDocs picks it up properly and replaces the link for us) or if a MkDocs configuration issue.
If it's not the last option, I'll be happy to PR away once I get guidance.

**Comment by estruyf** [comment]
Thanks @baywet this has been fixed
