### ISSUE TITLE
PropertyFieldTermPicker: Tags icon styling issue on IE11 

### ISSUE THREAD

**Issue by estruyf** [SharePoint/sp-dev-fx-property-controls#193]
#### Category
[ ] Enhancement
[x] Bug
[ ] Question

#### Version

Please specify what version of the library you are using: [latest]

#### Expected / Desired Behavior / Question

On IE11 there is a styling issue with the tags icon rendering.

![Screenshot 2019-08-14 10 47 35](https://user-images.githubusercontent.com/2900833/63007440-f068c480-be80-11e9-9f81-829b73d1bdff.png)

**Comment by AJIXuMuK** [comment]
@estruyf I believe it hasn't been fixed...
