### ISSUE TITLE
PropertyFieldListPicker - type error in ** this.context ** in the sample object properties.

### ISSUE THREAD

**Issue by IsYet1** [SharePoint/sp-dev-fx-property-controls#2]
#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [   
Beta 1
]

#### Expected / Desired Behavior / Question
this.context in PropertyFieldListPicker would map to a valid or included type.

#### Observed Behavior
Get error that **type of property 'context' are incompatible**.
Error output:
`
file: 'file:///c%3A/Dev/sp/lrn/spfx/no-framework00/src/webparts/noFramework00/NoFramework00WebPart.ts'
severity: 'Error'
message: 'Argument of type '{ label: string; context: WebPartContext; onPropertyChange: any; properties: INoFramework00WebPar...' is not assignable to parameter of type 'IPropertyFieldListPickerProps'.
  Types of property 'context' are incompatible.
    Type 'WebPartContext' is not assignable to type 'IWebPartContext'.
      Types of property 'httpClient' are incompatible.
        Type 'HttpClient' is not assignable to type 'HttpClient'. Two different types with this name exist, but they are unrelated.
          Types have separate declarations of a private property '_httpClientBase'.'
at: '59,55'
source: 'ts'
`

This is in a newly created No Framework project.
Using the latest Generator.
I get the same error in a React based project.

#### Steps to Reproduce
Install the packages.
Add the imports, etc.
Add the PropertyField sample code to the existing groupFields collection.

Thanks!

**Comment by estruyf** [comment]
Thank you for reporting this.

It should be fixed with the beta 2 release. Can you update the `@pnp/spfx-property-controls` version to `1.0.0-beta.2` and see if this solves your issue?

**Comment by IsYet1** [comment]
Sure thing.
You probably know this already: I was able to get this to work by changing:
Line 95 of IPropertyFieldTermPicker.d.ts 
to context: any;

I'll try the beta.2.

**Comment by estruyf** [comment]
The problem was related to a combination of v1.2.0 and v1.3.0. Atm, it installed two versions, so it saw two interfaces with the same name. That was causing the issue. You change to `any` will indeed work, but is not a good fix.

**Comment by IsYet1** [comment]
any fixes everything, right? ;-) 

I updated the package it works fine.
Thanks.

That should fix all of the Property controls. I'm going to start playing around with the Content controls next.

**Comment by mrcpgn** [comment]
I have the same problem with @pnp/spfx-property-controls 2.3.0, PropertyFieldSitePicker context
