### ISSUE TITLE
New Control: Rich text editor for React

### ISSUE THREAD

**Issue by rahulsuryawanshi** [SharePoint/sp-dev-fx-property-controls#20]
Rich text is essential in every application. I haven't seen Rich Text Editor control in Office-UI-Fabric-React which can be used in SFPx Web Parts. This control will be great addition to reusable control list.

Thanks in advance.

**Comment by AJIXuMuK** [comment]
Hi @rahulsuryawanshi,

Do you have any specific use case for Rich Text Editor in Web Part Property Pane?

**Comment by rahulsuryawanshi** [comment]
Hi @AJIXuMuK 
This is not for Property pane but for SPFx Web Part. TextField control of Office-UI-Fabric-React currently doesn't support Rich text. So checking if there is any plan for custom control which support Rich text.

**Comment by AJIXuMuK** [comment]
Hi @rahulsuryawanshi ,

In that case you should move this issue to [sp-dev-fx-controls-react](https://github.com/SharePoint/sp-dev-fx-controls-react) repo. This one is used for Property Pane controls.

**Comment by estruyf** [comment]
This control was already requested. You can follow the discussion in the React Controls repo: https://github.com/SharePoint/sp-dev-fx-controls-react/issues/20

I'm closing this issue.
