### ISSUE TITLE
How/where do I define the PropertyFieldOrder items array?

### ISSUE THREAD

**Issue by Panoone** [SharePoint/sp-dev-fx-property-controls#203]
#### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question

#### Version

Please specify what version of the library you are using: [1.16.0]

#### Question
Firstly, please excuse my  ignorance.

I have defined my items array within the control's properties (shown below). But this results in the items remaining static within the property pane.

How/where do I declare my items array and reference it within the control properties? The example in the docs uses `items: this.properties.orderedItems` but I'm unsure how to utilise it.

`PropertyFieldOrder("orderedItems", {
                  key: "orderedItems",
                  label: "Ordered Items",
                  items: [
                    {"text": "Cat", "iconName": "Cat"},
                    {"text": "Pig", "iconName": "Savings"},
                    {"text": "Human", "iconName": "Running"},
                    {"text": "Robot", "iconName": "Robot"},
                    {"text": "Dog", "iconName": "FangBody"}
                  ],
                  textProperty: "text",
                  properties: this.properties,
                  onPropertyChange: this.onPropertyPaneFieldChanged
                })`

**Comment by AJIXuMuK** [comment]
Hi @Panoone!
In your example items are hardcoded right inside Property Pane definition. In that case they will be static.
You need to add a new property to your web part and use it:
```typescript
export interface IOrderItem
{
  text: string;
  iconName: string;
}

// in web part properties interface:
orderedItems: IOrderItem[];

// in web part's onInit:
this.properties.orderedItems = [ {"text": "Cat", "iconName": "Cat"}, {"text": "Pig", "iconName": "Savings"}, {"text": "Human", "iconName": "Running"}, {"text": "Robot", "iconName": "Robot"}, {"text": "Dog", "iconName": "FangBody"} ]

// and in property pane initialization:
PropertyFieldOrder("orderedItems", { key: "orderedItems", label: "Ordered Items", items: this.properties.orderedItems, textProperty: "text", properties: this.properties, onPropertyChange: this.onPropertyPaneFieldChanged })
```

**Comment by Panoone** [comment]
@AJIXuMuK thanks for that! You're a champion. 🥇
