### ISSUE TITLE
PropertyFieldPeoplePicker not triggering ComponentDidUpdate

### ISSUE THREAD

**Issue by robiharid** [SharePoint/sp-dev-fx-property-controls#206]
Not sure why adding People with this picker does not trigger CompDidUpdate in the underlying React component. Triggering the update or refreshing the page shows that props updates successfully.

Do you have to explicitly state `this.properties.people = this.properties.people `in the `onPropertyPaneFieldChanged` property?

**Comment by AJIXuMuK** [comment]
Hi @robiharid,

Could you please provide a bit more explanation on what you're trying to achieve?

When the value is changed in `PropertyFieldPeoplePicker` we're updating the appropriate property of the web part and calling `onPropertyChange`. This actions lead to web part's re-render.

```typescript
if (this.props.onPropertyChange && newValue) {
      this.props.properties[this.props.targetProperty] = newValue;
      this.props.onPropertyChange(this.props.targetProperty, oldValue, newValue);
// Other code
```

**Comment by robiharid** [comment]
> Hi @robiharid,
> 
> Could you please provide a bit more explanation on what you're trying to achieve?
> 
> When the value is changed in `PropertyFieldPeoplePicker` we're updating the appropriate property of the web part and calling `onPropertyChange`. This actions lead to web part's re-render.
> 
> ```ts
> if (this.props.onPropertyChange && newValue) {
>       this.props.properties[this.props.targetProperty] = newValue;
>       this.props.onPropertyChange(this.props.targetProperty, oldValue, newValue);
> // Other code
> ```

hI @AJIXuMuK thanks for replying,

My problem was that the change was not triggering ComponentDidUpdate in my underlying Component.tsx do you know how I can force a rerender?

**Comment by AJIXuMuK** [comment]
Could you please check that the `render` method of the web part is called after property change?
If yes - check if you're providing changed data to the component.
React may be smart enough to skip component's re-render if it's not needed.
