### ISSUE TITLE
Use any  spfx-property-controls inside the custom PropertyFieldCollectionData control render

### ISSUE THREAD

**Issue by DA-Mena** [SharePoint/sp-dev-fx-property-controls#207]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://sharepoint.github.io/sp-dev-fx-property-controls/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question

So for the PropertyFieldCollectionData control we are able to render a custom element whether it's a react element or an html element. I'd like to use one of the main controls of the sp-dev-fx-property-controls package as one of those elements within PropertyFieldCollectionData's fields.

Do I need to make my own "wrapper" for this control that just gets the .js file?

**Comment by AJIXuMuK** [comment]
Hi @DA-Mena,
Controls from this repo are implemented to be used as Property Pane controls, not as standalone components that can be added as children to other components.
For that purposes you can take a look at [React Reusable Controls](https://github.com/SharePoint/sp-dev-fx-controls-react). 
Maybe the component you need is implemented there.

**Comment by DA-Mena** [comment]
I guess I'll look around npmjs. Color picker is not in react controls.

**Comment by russgove** [comment]
Hey, you can use the office-ui-fabric color picker for this.
Just import it:
import { ColorPicker } from "office-ui-fabric-react";


and then you can set your custom field up like this:
 {
                      id: "color",
                      title: "Color",
                      type: CustomCollectionFieldType.custom,
                      onCustomRender: (field, value, onUpdate, item, itemId, onError) => {

                        return (
                          React.createElement("div", null,
                            React.createElement(ColorPicker, {
                              key: itemId,
                              color: value,
                              onChange: (event: React.FormEvent<HTMLInputElement>,color:any) => {
                                debugger;
                                onUpdate(field.id, color.str);
                              }
                            })
                          )
                        );
                      }
                    },

**Comment by DA-Mena** [comment]
Thanks @russgove
