### ISSUE TITLE
PropertyFieldListPicker add optional property for target site

### ISSUE THREAD

**Issue by joelfmrodrigues** [SharePoint/sp-dev-fx-property-controls#21]
#### Category
[ X] Enhancement

[ ] Bug

[ ] Question

#### Expected / Desired Behavior / Question
Add an optional property to allow the target site url to be configured so that the component can load lists from a different site (it is a common development scenario to have components that read data from the root site for example)

#### Observed Behavior
Control default to loading lists from the current site.

Happy to help if the suggestion gets approved.
Thanks,
Joel

**Comment by joelfmrodrigues** [comment]
Started working on this

**Comment by joelfmrodrigues** [comment]
Finally managed to complete this, sorry I was too busy and it took a long time

**Comment by estruyf** [comment]
Thanks @joelfmrodrigues, this got merged and released in v1.8.0 today.
