### ISSUE TITLE
Add People picker control using SPFx extension on list view command set bar

### ISSUE THREAD

**Issue by Sampadaak2613** [SharePoint/sp-dev-fx-property-controls#220]
Below is the scenario on which I want to work on. 
Select the document, 
Click on command button from command bar 
Open popup Add 3 people picker control on the same which will fetch the data from the list person/group column Update the values in people picker.  
Any inputs on this?
I want to use pnp/spfx-property-controls in .ts file of command set extension.
On click of command, popup should get opened and in that popup , i want to display this people picker control. I do not want to use react component. 
I have referred the url [https://sharepoint.github.io/sp-dev-fx-property-controls/controls/PropertyFieldPeoplePicker/](url), and tried to add that code in .ts file but it is giving an error on "this.onPropertyPaneFieldChanged,"
Let me know how to accommodate this code in .ts file.

**Comment by AJIXuMuK** [comment]
Hi @Sampadaak2613,

Property Controls are developed to be used in SPFx Web Part Property Pane only.
There is another repo for web parts and extensions - [Reusable React Controls](https://sharepoint.github.io/sp-dev-fx-controls-react/)

You have to be familiar with React development to use these components in your command set customizer.

In few words,
You'll need to install the module in your project as mentioned in the documentation linked above.
 Then, you'll need to create you "Popup" component. I would recommend to create it in a separate `.tsx` file that allows combined markup and TypeScript code.
In this file you'll need to `import` needed component - in your case `PeoplePicker`.
And then, in `render` method you'll be able to use it just like `<PeoplePicker ... />`

Let me know if it makes sense.
