### ISSUE TITLE
PeoplePicker. Check if Label is null and if so don't render it.

### ISSUE THREAD

**Issue by Luksys5** [SharePoint/sp-dev-fx-property-controls#30]
Category
[ x] Enhancement

[ ] Bug

[ ] Question

Version 1.3.0

Description
When label is empty it's still being rendered and occupy necessary space

**Comment by estruyf** [comment]
The fix for this has been added to the latest DEV build, and is scheduled to be released with `v1.4.1`. The same logic has been implemented for other fields like term picker, color picker, ...
