### ISSUE TITLE
PropertyFieldPeoplePicker Validation does not work as expected.

### ISSUE THREAD

**Issue by SamipPatel** [SharePoint/sp-dev-fx-property-controls#33]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Expected / Desired Behavior / Question
Added validation function to onGetErrorMessage property of a PropertyFieldPeoplePicker field.  Wrote the validation function to fail on purpose and expected to see error message in property pane under the people picker field.

#### Observed Behavior
No error message was displayed.  

#### Notes:
  1. Specifically, it looks like there is an issue on line 162 of PropertyFieldPeoplePickerHost.tsx where the error message logic is only run if the result is 'undefined'.
  2. I updated that line locally to see what the error message would look like and observed that the css was not rendering as expected.  The people picker did not have a red outline and the error message was not displayed in red text.

**Comment by estruyf** [comment]
Thanks for reporting this, I have done the changes to the property control. It is planned to be released in the next version `v1.4.1`. Feel free to already test it out by using the beta version. Instructions for installing the beta version can be found here: https://sharepoint.github.io/sp-dev-fx-property-controls/beta/
