### ISSUE TITLE
MultiSelect acts like a simple Dropdown

### ISSUE THREAD

**Issue by OskarSol** [SharePoint/sp-dev-fx-property-controls#34]
#### Category
[ ] Enhancement

[x] Bug

[x] Question

#### Version
Hi, 
I'm trying to use the latest version of the MultiSelect control in my SP2016 onpremise environment. If I try to include the very basic example into my project it only shows up a DropdownControl. Is this control generally capable to work in an onpremise environment? And if so, how? ;-) 

![grafik](https://user-images.githubusercontent.com/37073408/36976731-ecbd7264-207e-11e8-9268-dbcf16d21b13.png)

The code I used:

`PropertyFieldMultiSelect('multiSelect', {
                                key: 'multiSelect',
                                label: "Multi select field",
                                options: [
                                  {
                                    key: "EN",
                                    text: "EN"
                                  },
                                  {
                                    key: "FR",
                                    text: "FR"
                                  },
                                  {
                                    key: "NL",
                                    text: "NL"
                                  }
                                ],
                                selectedKeys: this.properties.multiSelect
                              })`

And of course with the correct properties:

`multiSelect: string[];`

Other Controls like the DateTimePicker are working fine...

**Comment by OskarSol** [comment]
I tryied to set up the two same basic projects. One with the yeoman generator for SPOnline and one with the SP2016+Online template. As expected the SPOnline project works fine. 

In the SP2016 project I had to adjust the localized resource from ` "PropertyControlStrings": "./node_modules/@pnp/spfx-property-controls/lib/loc/{locale}.js"` to `"PropertyControlStrings": "../node_modules/@pnp/spfx-property-controls/lib/loc/{locale}.js"` because of the following error

![grafik](https://user-images.githubusercontent.com/37073408/36981596-df9d6bca-208d-11e8-8f98-c6b1cd0d1b06.png)

But the issue remains the same: the expected MultiSelect control renders as simple DropDown control.

**Comment by estruyf** [comment]
Thanks @OskarSol for reporting this. The controls have a dependency on SPFx version v1.3.0 at the moment. The version used for on-premises is v1.1.0 which has a different Office UI Fabric version dependency which does not have multi-select included. So that is the reason you see this behavior.

**Comment by OskarSol** [comment]
Okay that makes sense for me, thank you for the quick answer! :-) So I will end up by building myself a custom control. 

Is this information (the used PSFx version) somewhere written down that I overlooked? If not, it would be really nice to have this information somewhere in the readme.

**Comment by estruyf** [comment]
I have just added it to the documentation to make it clear.
