### ISSUE TITLE
People Picker console error

### ISSUE THREAD

**Issue by dgrooms** [SharePoint/sp-dev-fx-property-controls#47]
#### Category
[ ] Enhancement

[ X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [  1.4.2       ]

#### Expected / Desired Behavior / Question
Typing a partial user name returns that user in the suggestions pane

#### Observed Behavior
no user is displayed and a script error appears in the console

#### Steps to Reproduce
1. WIth the control in a web part, open the properties panel.
2. Add a user to the control
3. save the page containing the web part
4. edit the page again and remove the user from the control
5. now type the name of a known user
6. most of the time this sequence will trigger the error.

![image](https://user-images.githubusercontent.com/29958427/38829085-a69c7026-417d-11e8-974b-774bdd5638b4.png)

Looking at the source code leads me to believe that under some conditions, the searchPeople method in SPPeopleSearchService.ts  is called with the 'this' object undefined.

**// the method throwing the error :**

 public searchPeople(query: string, principalType: PrincipalType[]): Promise<Array<IPropertyFieldGroupOrPerson>> {
    if (Environment.type === EnvironmentType.Local) {
      // If the running environment is local, load the data from the mock
      return this.searchPeopleFromMock(query);
    } else {
      // If the running env is SharePoint, loads from the peoplepicker web service

**// this line throws the error that "this.context.pageContext" is undefined**

      const userRequestUrl: string = `${this.context.pageContext.web.absoluteUrl}/_api/SP.UI.ApplicationPages.ClientPeoplePickerWebServiceInterface.clientPeoplePickerSearchUser`;
      
This was reproducible in both Chrome and FireFox

Dave

**Comment by estruyf** [comment]
Thanks @dgrooms for reporting it. I'll take a look at it.

**Comment by estruyf** [comment]
This has been fixed and is scheduled to be released in `v1.5.1`. Can you check if the fix worked by installing the beta version? More information about installing beta versions can be found here: https://sharepoint.github.io/sp-dev-fx-property-controls/beta/

**Comment by dgrooms** [comment]
This looks to have fixed it from my testing.
Thanks for the quick response !

David Grooms

Concurrency, Inc.

**Comment by estruyf** [comment]
Thanks for checking this!
