### ISSUE TITLE
Use components outside of a spfx project

### ISSUE THREAD

**Issue by koehrlenguillaume** [SharePoint/sp-dev-fx-property-controls#51]
#### Category
[ ] Enhancement

[ ] Bug

[x ] Question

#### Version

Please specify what version of the library you are using: [1.5.0]

#### Question

I would like to know, if there is a way to use these components outside of a spfx context ? 
In my case I would like to create a [Panel](https://developer.microsoft.com/en-us/fabric#/components/panel) and add some controls in it. 
To do that I created a React project and added the built files in a SharePoint page. 
My problem is when I'm trying to integrate these react components in my project, it doesn't build 
 --> spfx context

Thanks!

**Comment by estruyf** [comment]
Hi @koehrlenguillaume that would not be possible, these controls only work in the context of SPFx as they are created for the web part property pane and also make use of the `pageContext` object.

**Comment by koehrlenguillaume** [comment]
Thanks for the answer @estruyf !
