### ISSUE TITLE
PropertyFieldColorPicker Palette Icon alignment issue in IE11

### ISSUE THREAD

**Issue by sprider** [SharePoint/sp-dev-fx-property-controls#56]
#### Category
- [ ] Bug

#### Version
1.5.1 and above including beta 

#### Expected 
Fix the alignment issue as you see below or open the color palette as a callout 
<img width="334" alt="chrome" src="https://user-images.githubusercontent.com/21008316/39259843-2a38269a-487d-11e8-8ba9-318bf807230e.png">

#### Observed Behavior
In IE11 the PropertyFieldColorPicker Palette Icon seems to hide when active which creates mild confusion on closing. 
<img width="328" alt="ie 11" src="https://user-images.githubusercontent.com/21008316/39259860-318eebcc-487d-11e8-827e-89dee41a12bc.png">

#### Steps to Reproduce
1. Create a SPFx webpart
2. Install sp-dev-fx-property-controls package as mentioned in https://sharepoint.github.io/sp-dev-fx-property-controls/
3. Add PropertyFieldColorPicker property  
4. Execute the app using gulp serve
5. Open the local workbench page in IE11 and add the app 
6. Edit the PropertyFieldColorPicker property
7. Notice the icon alignment issue  

Thanks!

**Comment by sprider** [comment]
Please verify in Edge browser as well

**Comment by sprider** [comment]
Sometimes the icon is hiding in windows when i have other web parts in the page.

<img width="338" alt="screen shot 2018-05-01 at 8 36 41 am" src="https://user-images.githubusercontent.com/21008316/39475738-0d8473a4-4d1f-11e8-9643-bca5aee74a97.png">

**Comment by estruyf** [comment]
I cannot seem to reproduce this issue in Edge. @thechriskent can you?

**Comment by thechriskent** [comment]
I'm not seeing any issues in Edge or IE.

Here is a screenshot of a webpart using this control alongside other webparts on a communication site using the Edge browser:

![image](https://user-images.githubusercontent.com/8364109/39763050-1b739338-52aa-11e8-87be-3cfe49dbee17.png)

Here is the control where multiple property pages are being used (as in your screenshot) also in Edge:

![image](https://user-images.githubusercontent.com/8364109/39763446-13380f40-52ab-11e8-9511-c724c63ef5be.png)


I'm going to close the issue for now, but if you continue to experience these issues please feel free to reopen with any additional details about when this is happening. Thanks!
