### ISSUE TITLE
1.6.0 Release Date 

### ISSUE THREAD

**Issue by sprider** [SharePoint/sp-dev-fx-property-controls#61]
#### Category
- [ ] Question

#### Version
1.6.0

Hi Team,
Any idea about the expected release date for 1.6.0? 

Thanks!

**Comment by estruyf** [comment]
Depends on testing and open issues. At the moment there is still one to follow-up. So try to schedule the release later this week or next week.

**Comment by sprider** [comment]
Sure, Thank you Elio.
