### ISSUE TITLE
Taxonomy picker for enterprise

### ISSUE THREAD

**Issue by kristianbkjaer** [SharePoint/sp-dev-fx-property-controls#70]
#### Category
- [x ] Enhancement
- [ ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [1.6.0]

#### Expected / Desired Behavior / Question
When opening the term picker list, today the complete tree is expanded.
This does not work for comprehensive trees of taxonomy. We intend to use it for our organisation tree with about 3700 nodes in the tree. This loads extremely slow and picking the right term is a nightmare with a huge vertical scrollbar and bad performing scrolling (especially in IE).
Enhancement would be:
- Having the option to expand and collapse the nodes (not leaf nodes) in the taxonomy tree (just as in good old SharePoint ;). The tree should be collapsed as default and only the immediate children of the root should be visible.
- Asynchronous load of subtrees. The subtrees should not be loaded until the user actually expand the node to avoid pre-loading of extreme trees. The best would be that the level shown is loaded +1 to maximize usability (e.g. load is always one level "ahead" of user).

Use case: We have our (quite comprehensive) organisation tree synchronized as a termset (manually as the flat list provided by SharePoint in predefined termset "Department" is useless when it is flat). The user profiles have a custom property filled with the term corresponding to their organisational belonging. On pages we have developed (looking forward to the announced "Page details") a property pane where we use this control to pick an organisation unit, the page belongs to. The we use that property to:
- Roll-up content (based on search) from specific organisation (sub)trees
- Roll-up targeted content to user based on their profile data

#### Steps to Reproduce
Create a huge termset and use it in this control, then you will quickly see the bad usability of working with the control.

**Comment by estruyf** [comment]
Hi @kristianbkjaer this is good feedback this will require to rewrite the whole component. A good thing is that the PnP team recently released the `@pnp/sp-taxonomy` for the `PnPJS` library [https://pnp.github.io/pnpjs/sp-taxonomy/index.html](https://pnp.github.io/pnpjs/sp-taxonomy/index.html). This allows us to make Managed Metadata calls a lot easier and we could use it in our components.

**Comment by kristianbkjaer** [comment]
Sounds great. I really hope for this feature in an upcoming release, but understand that it might be good to wait for the api update. I guess asynchronous load of subtrees become easier then?
Keep crossing my fingers :)

**Comment by estruyf** [comment]
@kristianbkjaer no API update, it is a new part of the PnP JS Core library.

**Comment by kristianbkjaer** [comment]
Yes, that was also what I meant (but did not write ;)) But the rest of my comment makes sense right?

**Comment by estruyf** [comment]
Yes indeed @kristianbkjaer (y)

**Comment by kristianbkjaer** [comment]
Any news on this? Is it assigned to some roadmap or being worked on?
*cross my fingers here* :)

**Comment by estruyf** [comment]
At the moment it's not assigned to anyone.

**Comment by estruyf** [comment]
The control that @AJIXuMuK created will be available in version `1.14.0`. @kristianbkjaer feel free to test out the latest beta version to see if the `PropertyFieldEnterprisePicker` fits your needs.

More information on how to install a beta version can be found here: https://sharepoint.github.io/sp-dev-fx-property-controls/beta/
