### ISSUE TITLE
Validation for PropertyFieldCollectionData

### ISSUE THREAD

**Issue by niranjan747** [SharePoint/sp-dev-fx-property-controls#74]
Category
- [x] Enhancement
- [ ] Bug
- [ ] Question

Version

Please specify what version of the library you are using: [ 1.6.0 ]

Expected / Desired Behavior / Question
I want to perform some validations on Collection Data, for this i require callback option for validation of Collection Data. Either of onGetErrorMessage or onPropertyChange would help. These properties are available in some of the controls such as listPickers fieldPicker etc..

Would appreciate any help on how to get these properties for PropertyFieldCollectionData as well.

Thanks!

**Comment by estruyf** [comment]
@niranjan747 Thank you for testing out the controls. This could indeed be a good enhancement.

**Comment by splearner** [comment]
Kindly help me out to validate the URL in collection Data.

**Comment by estruyf** [comment]
Custom validation is coming for the string, number, icon and URL fields.

![collectiondata-validation](https://user-images.githubusercontent.com/2900833/43849948-ed0a6eb0-9b36-11e8-98c9-7615003a4d0d.gif)

**Comment by estruyf** [comment]
This will be available as of version 1.9.0. The beta can already be tested: https://sharepoint.github.io/sp-dev-fx-property-controls/beta/
