### ISSUE TITLE
You should put out demos for these

### ISSUE THREAD

**Issue by wils0nk3** [SharePoint/sp-dev-fx-property-controls#75]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://sharepoint.github.io/sp-dev-fx-property-controls/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question

It would help with the testing...

**Comment by VesaJuvonen** [comment]
This repository is actually also a SharePoint Framework client-side web part, which demonstrates usage of these controls. These are also widely used in the SharePoint Starter Kit and in many other samples - See https://github.com/SharePoint/sp-starter-kit. Closing this for now, but absolutely also open for input around what else is missing or should be there. Thx.
