### ISSUE TITLE
[PropertyFieldDateTimePicker] Add ability to hide labels in front of the pickers

### ISSUE THREAD

**Issue by tsekityam** [SharePoint/sp-dev-fx-property-controls#77]
#### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: 1.7.0

#### Expected / Desired Behavior / Question
I expected the `PropertyFieldDateTimePicker` should have a look and feel similar to the date time picker we had in SharePoint list.
<img width="587" alt="screen shot 2018-07-04 at 5 01 50 pm" src="https://user-images.githubusercontent.com/3814422/42267666-31af730e-7fac-11e8-9c67-f3d3c6b9bb58.png">

I would like to suggest add a property to the control, such that user can disable the label. 

#### Observed Behavior
Now we have labels before date time pickers property control, however, no any other default property controls nor pnp property controls has label in front of the controls. If we use date time picker control together with another property controls, the date time picker control looks odd.

<img width="329" alt="screen shot 2018-07-04 at 5 15 48 pm" src="https://user-images.githubusercontent.com/3814422/42268391-ee51045e-7fad-11e8-9ec7-4c038c4b8777.png">

#### Steps to Reproduce
N/A

**Comment by estruyf** [comment]
Thanks @tsekityam for the suggestion!

**Comment by tsekityam** [comment]
I will write a patch to remove those labels from the control.

**Comment by estruyf** [comment]
This has now been implemented in the latest beta. Feel free to test it out.

Here you can read how you can install the latest beta: https://sharepoint.github.io/sp-dev-fx-property-controls/beta/

Add the property `showLabels` with the value set to `false` to the `PropertyFieldDateTimePicker` property pane control in order to hide the labels.

**Comment by estruyf** [comment]
This has just been released in version `1.15.0`.
