### ISSUE TITLE
[PropertyFieldOrder] Appending to an array doesn't reflect in order

### ISSUE THREAD

**Issue by Katli95** [SharePoint/sp-dev-fx-property-controls#81]
#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
_Pretty sure this is a bug because I'd expect changing the property would affect this field_
#### Expected / Desired Behavior 
I expected to be able to sort an array that drew it's contents from the PropertyFieldMultiSelect field.

#### Observed Behavior
Once I choose an option with the PropertyFieldMultiSelect it doesn't show up in the PropertyFieldOrder until I refresh my browser window. (all of this is on a hosted SP workbench.

#### Steps to Reproduce
1. Add both of these field controls and connect them to the same property. 
2. Try selecting items from the MultiSelect and see if the OrderField updates

> quick sidenote: 
My actual flow is actually slightly more complicated as I am dynamically loading up the MultiSelect options with the @pnp/sp library.

Thanks!

**Comment by estruyf** [comment]
Thanks @Katli95 for reporting this.

@thechriskent could you check this one?

**Comment by estruyf** [comment]
@Katli95 the issue got fixed and will be in version 1.9.0 of the controls release.

Here you can see the result:
![orderfield-async](https://user-images.githubusercontent.com/2900833/43893761-5cae8258-9bd0-11e8-818b-910a64e04d94.gif)

You can always test out the latest beta: https://sharepoint.github.io/sp-dev-fx-property-controls/beta/

**Comment by Katli95** [comment]
Awesome! Love the work your doing and look forward to participating myself. I would have fixed the issue myself but I feel reluctant to alter any of the source code as I've only been working in Web Development since the SPFx got released in February last year.
