### ISSUE TITLE
French localization

### ISSUE THREAD

**Issue by estruyf** [SharePoint/sp-dev-fx-property-controls#84]
#### Category
[x] Enhancement
[ ] Bug
[ ] Question

Add Dutch localization labels

**Comment by sebastienlevert** [comment]
I can take care of this one @estruyf! Anything I should know before I start?

**Comment by estruyf** [comment]
@sebastienlevert, that would be great!

**Comment by estruyf** [comment]
Version `1.12.0` has just been released.
