### ISSUE TITLE
PropertyPaneMultiSelect is not retaining preselected values

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-fx-property-controls#85]
The problem is the once i set the values and then save the changes, the next time when i open the webpart configuration the multiselect values are not retained.

```

                PropertyFieldMultiSelect('selectedColumns', {
                  key: 'selectedColumns',
                  label: "Multi select field",
                  options: this.ddlColumnOptions,
                  selectedKeys: this.properties.selectedColumns
                })
```
Here is the screen shot , the value for normal dropdown are retained.But it is not working for multiselect

![image](https://user-images.githubusercontent.com/11780473/43508713-4b67b78c-958e-11e8-871e-abc96a623c36.png)

Code on start : 
```

  protected async onPropertyPaneConfigurationStart(): Promise<any> {
    debugger;
    let lists:IPropertyPaneDropdownOption[]=await this.getAllList();
    this.ddlListOptions=lists;
    this.render();
    this.context.propertyPane.refresh();
    let views:IPropertyPaneDropdownOption[]=await this.getAllViews()
    this.ddlViewOptions=views;
    this.render();
    this.context.propertyPane.refresh();
    let columns:IPropertyPaneDropdownOption[]=await this.loadColumns();
    this.ddlColumnOptions=columns;
    this.render();
    this.context.propertyPane.refresh();
  }
```

**Comment by estruyf** [comment]
This is an issue in the Office UI Fabric control used behind the scenes which seems to have issues when async options are provided. I did an update to the control so that it is supported.

Here you can see the result:
![multiselect-async](https://user-images.githubusercontent.com/2900833/43892497-65100024-9bcc-11e8-8ee8-1a9e3998c26a.gif)
