### ISSUE TITLE
PropertyFieldPeoplePicker select only from sitecollection

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-fx-property-controls#9]
#### Category
[x ] Enhancement

[ ] Bug

[ ] Question

PropertyFieldPeoplePicker should have an option to only let you select users from the current sitecollection.

**Comment by estruyf** [comment]
@russgove this has finally been implemented. I have introduced a new `targetSiteUrl` property on the `PropertyFieldPeopleFinder` control to allow you to search users only on specified sites. 

If you want, you can test it out in the latest beta version of `v1.13.0`. More information about how to install a beta version can be found here: https://sharepoint.github.io/sp-dev-fx-property-controls/beta/
