### ISSUE TITLE
PropertyFieldPeoplePicker - No suggestions returned when using Security Groups, Multi-select and NO duplicates.

### ISSUE THREAD

**Issue by petecuttriss** [SharePoint/sp-dev-fx-property-controls#90]
#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Expected / Desired Behavior / Question
Using the PropertyFieldPeoplePicker, I have set it so that allowDuplicates is false, multiSelect is true and the principalType is PrincipalType.Security.   I would expect to be able to select multiple security groups.  After making a single initial selection, and then when I begin typing for a second selection, I would expect to see suggested groups.

#### Observed Behavior
When no groups are selected, I can being typing and get suggested security groups as expected.  Once I make a selection and begin to look for a second security group I get 'No results found'.    If I change the PropertyFieldPeoplePicker so that allowDuplicates is set to true (or add further PrincipalTypes), I can enter and receive suggestions for more than one security group.

#### Steps to Reproduce
Add a PropertyFieldPeoplePicker control to a web part project and configure it so that:
- allowDuplicate: false,
- multiSelect: true,
- principalType: [PrincipalType.Security]

e.g.
`PropertyFieldPeoplePicker('securityGroups', {
label: 'NO Duplicates, Multi-select, PrincipalType.Security',
                  initialData: this.properties.securityGroups,
                  allowDuplicate: false,
                  multiSelect: true,
                  principalType: [PrincipalType.Security],
                  onPropertyChange: this.onPropertyPaneFieldChanged,
                  context: this.context,
                  properties: this.properties,
                  onGetErrorMessage: null,
                  deferredValidationTime: 0,
                  key: 'securityGroupsFieldId'
                })`

Run the project using **gulp serve** and then browse to the SharePoint Online Workbench _layouts/15/workbench.aspx.

Edit the web part and select a security group from the PropertyFieldPeoplePicker.   Then attempt to select a second security group which you know exists.

![issue_example](https://user-images.githubusercontent.com/4825764/44129877-b20eb79a-a09e-11e8-86f9-e711510ce3fa.PNG)

Thanks for these controls and all your efforts, they're great.

**Comment by estruyf** [comment]
Thanks @petecuttriss for reporting this. I have fixed this bug and will be available in version `1.10.0`. You can already test out the beta via: https://sharepoint.github.io/sp-dev-fx-property-controls/beta/

![security-group](https://user-images.githubusercontent.com/2900833/45166065-72bf2200-b1f6-11e8-8db7-b46c5dac8fe2.gif)

**Comment by petecuttriss** [comment]
Hi Elio,

I've tested out this fix in the beta and it's working great.

Thanks
Pete

**Comment by estruyf** [comment]
Thanks for testing it!

Will close this issue. The release of the new version is planned later this week.
