### ISSUE TITLE
PropertyFieldPeoplePicker - Security groups come back with EntityType of FormsRole rather then SecGroup

### ISSUE THREAD

**Issue by petecuttriss** [SharePoint/sp-dev-fx-property-controls#93]
#### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question

#### Version

Please specify what version of the library you are using: [ 1.9.0  ]

#### Expected / Desired Behavior / Question
Hi, I'm using the PropertyFieldPeoplePicker in my web part solution to enable people to select from security groups [PrincipalType.Security].   When doing this, the object which is returned for the property, only has values for the description and fullName.   I would have expected to see fullName, login, id, and description values.

#### Observed Behavior
Using the browser developer tools I've looked at the XHR request and response.   In the response I can see that my Azure Security Groups are being returned with an EntityType value of "**FormsRole**" where I would have expected them to be "**SecGroup**".  Because of this the switch statement in the [SPPeopleSearchService.ts](https://github.com/SharePoint/sp-dev-fx-property-controls/blob/master/src/services/SPPeopleSearchService.ts), line 50, does not get a match and instead falls through to the default statement.

Because of this, neither the id or login values come back.   I was hoping to use the Id value to then query the Graph.

I've looked at a number of different group types coming back from Azure AD.  Only Office 365 groups seem to come back with an EntityType of SecGroup.   Azure Security Groups or Azure Email Enabled Security Groups are all coming back with an EntityType of FormsRole which seems unusual.

Does this seem correct, in that only Office 365 groups come back with the EntityType of SecGroup and Azure Security Groups come back with FormsRole?

Below are some screen shots showing the security group in Azure, the XHR response, and the resulting object:

![this props](https://user-images.githubusercontent.com/4825764/44634441-c07f9300-a989-11e8-8642-fb6a41ca1d90.PNG)

![azure_security_group](https://user-images.githubusercontent.com/4825764/44634443-c4abb080-a989-11e8-96fc-9a375add33cc.PNG)

![azure_entitytype_formsrole](https://user-images.githubusercontent.com/4825764/44634451-d0977280-a989-11e8-9d6d-656a01bde93d.PNG)

Thanks, these property controls are a great resource!

**Comment by estruyf** [comment]
Thanks @petecuttriss I will enhance the control.

**Comment by estruyf** [comment]
Fix is included in the latest beta which will be released in version `1.10.0`. More information to test out a beta version can be found here: https://sharepoint.github.io/sp-dev-fx-property-controls/beta/ Thanks again for reporting this.

**Comment by petecuttriss** [comment]
Hi Elio,

I've tested out this enhancement in the beta and it's working great.

Thanks
Pete

**Comment by estruyf** [comment]
Closing the issue as it got released in version `1.10.0`.
