### ISSUE TITLE
PropertyFieldCollectionData crashes browser while editing URL

### ISSUE THREAD

**Issue by Toonshorty** [SharePoint/sp-dev-fx-property-controls#99]
#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [1.11.0]

#### Observed Behavior
I haven't been able to narrow down what triggers this bug exactly, but when trying to copy in a SharePoint link with encoding (e.g. %20), the browser will lock up and throw an alert about a slow running script. I have replicated this in both Firefox and Chrome, however I can put special characters in most URLs, but SharePoint ones seem to be causing it problems.

#### Steps to Reproduce
Create a new application with a PropertyFieldCollectionData property, set one of the fields to `CustomCollectionFieldType.url`. Open the web part in the SP workbench and enter the following URL into the field:

> https://example.sharepoint.com/sites/intranet/Lists/Example%20List

The tab then locks up and throws a 'page unresponsive error'.

Interestingly, if I put a smaller URL like the following:

> https://example.sharepoint.com/Lists/Example%20List

Then the browser freezes momentarily for a couple of seconds, but then resumes - while the first link will freeze it completely. Replacing the %20 with spaces fixes the problem altogether.

That said, I have been able to paste in URLs containing %20 without any problem, the following will work fine for example:

> https://not.a.real.site/example%20page.aspx

I've also noticed that any URL containing %20 also fails validation, which is incorrect.

**Comment by estruyf** [comment]
Apparently, it causes some catastrophic backtracking issue in regex.

**Comment by estruyf** [comment]
Solved the bug by implementing a new RegEx statement. Would you be able to test it out in the latest beta? You find more information about installing a beta version here: https://sharepoint.github.io/sp-dev-fx-property-controls/beta/

**Comment by Toonshorty** [comment]
Fantastic, thanks Elio. The beta seems to be behaving much better.

**Comment by estruyf** [comment]
@Toonshorty thanks for verifying!

**Comment by estruyf** [comment]
Version `1.12.0` has just been released.
